### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by edgars** [wso2/docs-apim#1029]
Location : https://apim.docs.wso2.com/en/3.0.0/learn/api-controller/getting-started-with-wso2-api-controller/

For version 3.0 I am getting this error: 
apictl: Error in connecting. Reason: Post "https://172.29.130.5:9443/carbon/admin/login.jsp": Auto redirect is disabled

The previous apicli for 3.0 version documentation seems to be removed.

**Comment by Mariangela** [comment]
@npamudika , please provide your input with regard to this issue.

**Comment by npamudika** [comment]
Hi @edgars,

Could you please confirm what is the API Manager version you are using with APICTL 3.0.0 version?

Also please make sure the endpoints you have defined are correct as per https://apim.docs.wso2.com/en/3.0.0/learn/api-controller/getting-started-with-wso2-api-controller/#add-an-environment

**Comment by edgars** [comment]
Hi @npamudika and @Mariangela 

My environment is running on API 3.0, when I tried the apicli for this version, that used to work, I got it working.

Trying the new apictl, into an environment where the target is API-M 3.0 instead of 3.1, I am getting this error:

```
./apictl login dev -k
Username:admin
Password:
Error occurred while login :  Request didn't respond 200 OK: 404
```

My endpoints are following the doc:
`apictl add-env -e dev --registration https://172.29.130.5:9443/client-registration/v0.15/register --apim https://172.29.130.5:9443 --token https://172.29.130.5:8243/token`


Any thoughts?

Cheers

Edgar

**Comment by edgars** [comment]
When I try to add the env, using the register API v.014 I get this error:

```
./apictl login dev -k
Username:admin
Password:
apictl: Error in connecting. Reason: Post "https://172.29.130.5:9443/carbon/admin/login.jsp": Auto redirect is disabled
Exit status 1

```
Adding env command:

`apictl add-env -e dev --registration https://172.29.130.5:9443/client-registration/v0.14/register --apim https://172.29.130.5:9443 --token https://172.29.130.5:8243/token`

**Comment by npamudika** [comment]
> Hi @npamudika and @Mariangela
> 
> My environment is running on API 3.0, when I tried the apicli for this version, that in the past used to work well.
> 
> Trying the newest apictl (from 3.1.0 api-m release), into an environment where the target is API-M 3.0 instead of 3.1, I am getting this error:
> 
> ```
> ./apictl login dev -k
> Username:admin
> Password:
> Error occurred while login :  Request didn't respond 200 OK: 404
> ```
> 
> My endpoints are following the doc:
> `apictl add-env -e dev --registration https://172.29.130.5:9443/client-registration/v0.15/register --apim https://172.29.130.5:9443 --token https://172.29.130.5:8243/token`
> 
> Any thoughts?
> 
> Cheers
> 
> Edgar

Hello Edgar,

The newest **APICTL 3.1.0** version is **only** compatible with the **API Manager 3.1.0 version**. In order to use the version 3.1.0 of APICTL, you need to have the version 3.1.0 of the target APIM. When you try like that, you won't get this kind of an error. 

Please note that we have modified the environment values. Please follow https://apim.docs.wso2.com/en/3.1.0/learn/api-controller/getting-started-with-wso2-api-controller/#add-an-environment for the APICTL 3.1.0 release. 

If you want to keep the target APIM as 3.0.0, please use the version 3.0.1 (the latest patch release of the APICTL 3.0.0 version - https://github.com/wso2/product-apim-tooling/releases/tag/v3.0.1). Please follow https://apim.docs.wso2.com/en/3.0.0/learn/api-controller/getting-started-with-wso2-api-controller/#add-an-environment for more details for the APICTL 3.0.x version.

**Comment by npamudika** [comment]
> When I try to add the env, using the register API v.014 I get this error:
> 
> ```
> ./apictl login dev -k
> Username:admin
> Password:
> apictl: Error in connecting. Reason: Post "https://172.29.130.5:9443/carbon/admin/login.jsp": Auto redirect is disabled
> Exit status 1
> ```
> 
> Adding env command:
> 
> `apictl add-env -e dev --registration https://172.29.130.5:9443/client-registration/v0.14/register --apim https://172.29.130.5:9443 --token https://172.29.130.5:8243/token`

Please note the REST API versions are different for each APIM release. Since you said, you have the target APIM as 3.0.0, please use **v0.15** as guided in https://apim.docs.wso2.com/en/3.0.0/learn/api-controller/getting-started-with-wso2-api-controller/#add-an-environment with the **APICTL 3.0.1** version (https://github.com/wso2/product-apim-tooling/releases/tag/v3.0.1).

Please feel free to get back to us if you require any further assistance/clarification regarding this. We would happy to help you!

Thanks,
Naduni

**Comment by edgars** [comment]
@npamudika 

It worked add and to connect the environment, however to list the APis is not working:

./apictl list apis -e dev -k

I will try another option/solution, thanks.

Cheers

Edgar

**Comment by npamudika** [comment]
HI Edgar,

Ideally listing should also work. If you could provide me the endpoints of the dev environment, I could be able to help.

Thanks,
Naduni

**Comment by Mariangela** [comment]
@npamudika , please clarify whether there is a doc gap or doc bug based on this Git issue.

**Comment by npamudika** [comment]
@Mariangela we can close the issue. We have the mentioned details in the docs.
