### ISSUE TITLE
Some databases need to be corrected 

### ISSUE THREAD

**Issue by Prabhashi** [wso2/docs-apim#1106]
**Description:**
From API Manager 3.0 onwards it is using Shared_DB instead of having UM_DB and REG_DB. But in this documentation[1] it is still referring to UM_DB and REG_DB without indicating the Shared_DB. 

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/deploying-wso2-api-manager/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m/

**Affected Product Version:**
API Manager 3.0.0 / 3.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
This has already been fixed in:
- https://apim.docs.wso2.com/en/3.0.0/install-and-setup/deploying-wso2-api-manager/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m/#understanding-the-distributed-deployment-of-wso2-api-m
- https://apim.docs.wso2.com/en/3.1.0/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m/
- https://apim.docs.wso2.com/en/next/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m/
