### ISSUE TITLE
[Doc] Need to modify the documentation regarding sharing applications

### ISSUE THREAD

**Issue by riyazathali** [wso2/docs-apim#1229]
In the application sharing feature, the shared user will not be able to modify the application can only see/view the application. Current documentation[1] states "As a result of application sharing, users can view and modify applications and subscriptions belonging to other users in the same group"
Need an update on the documentation.
[1] https://docs.wso2.com/display/AM250/Sharing+Applications

**Comment by TanyaM** [comment]
Please fix this in 2.6.0 docs and check other versions as well

**Comment by Mariangela** [comment]
@TanyaM , please confirm whether we can use the following new description as the updated introduction to [1].

_"WSO2 API Manager provides the facility for users to share their applications and subscriptions with a specific logical group/groups such as an organization. As a result of application sharing, users in the group can view such shared applications.

WSO2 API Manager considers the organization name you enter when signing up to the API Store as the group ID. All the users specifying the same organization name belong to the same group. Therefore, such users that belong to a single group can view each others' subscriptions and applications provided that you have enabled group sharing. 

Only the application owner is capable of editing and deleting the application and not any other users in the shared group. However, if there is a requirement to edit/delete an application using a different user (for example due to a reason such as where the application owner left the organization etc.), you can achieve this by transferring the application ownership to that user who will be the new application owner.

Furthermore, only the application owner is allowed to generate keys for the application. However, the shared users can generate access tokens and therefore,  your user "admin" can see the **Regenerate** option which is used to regenerate the access tokens, but not the application keys.

WSO2 API Manager also provides the flexibility to change this default authentication implementation."_

[1] https://docs.wso2.com/display/AM250/Sharing+Applications

**Comment by TanyaM** [comment]
"However, if there is a requirement to edit/delete an application using a different user (for example due to a reason such as where the application owner left the organization etc.), you can achieve this by transferring the application ownership to that user who will be the new application owner." --> let's add this part as a separate note.
---------------------
 therefore, your user "admin" can see the Regenerate option which is used to regenerate the access tokens, but not the application keys. --> This part is specific to the support query that I have replied. user admin here is not the general admin user but a specific user in the customer's usecase. Hence we don't need this part.

**Comment by TanyaM** [comment]
However, if there is a requirement to edit/delete an application using a different user (for example due to a reason such as where the application owner left the organization etc.), you can achieve this by transferring the application ownership to that user who will be the new application owner. --> let's add this part as a separate note.
 
therefore, your user "admin" can see the Regenerate option which is used to regenerate the access tokens, but not the application keys. --> This part is specific to the support query that I have replied. user admin here is not the general admin user but a specific user in the customer's usecase. Hence we don't need this part.

**Comment by Mariangela** [comment]
@TanyaM , based on your feedback plan on adding the following into the documentation.

"WSO2 API Manager provides the facility for users to share their applications and subscriptions with a specific logical group or groups such as an organization. As a result of application sharing, users in the group can view such shared applications.

WSO2 API Manager considers the organization name you enter when signing up to the API Store as the group ID. All the users specifying the same organization name belong to the same group. Therefore, such users that belong to a single group can view each others' subscriptions and applications provided that you have enabled group sharing.

Only the application owner is capable of editing and deleting the application in the shared group. 

!!! Note
If there is a requirement to edit or delete an application using a different user (for example due to a reason such as where the application owner has already left the organization etc.), you can achieve this by transferring the ownership of the application to that user who will be the new application owner.

Furthermore, only the application owner is allowed to generate keys for a specific shared application. However, the shared users can generate access tokens and therefore, the shared users will see the **Regenerate** button which is used to regenerate the access tokens, but not the **Application Keys** button.

WSO2 API Manager also provides the flexibility to change this default authentication implementation."

**Comment by Mariangela** [comment]
Fixed in -

  | Fixed in 2.5.0 and 2.6.0
-- | --
https://github.com/wso2/docs-apim/pull/1294 | 3.0.0
https://github.com/wso2/docs-apim/pull/1295 | 3.1.0
https://github.com/wso2/docs-apim/pull/1296 | master
