### ISSUE TITLE
Provide valid steps to config entry nhttp.is.log.rotatable in deployment.toml

### ISSUE THREAD

**Issue by chaminda** [wso2/docs-apim#1278]
**Description:**
Correct the configurations mentioned under step 4 in [1].

nhttp.is.log.rotatable=true

[1] https://apim.docs.wso2.com/en/3.0.0/administer/product-administration/monitoring/logging/monitoring-http-access-logs/#configuring-access-logs-for-passthrough-or-nio-transports-in-api-gateway

**Comment by Mariangela** [comment]
Fixed in 

https://github.com/wso2/docs-apim/pull/1286 | 3.0.0
-- | --
https://github.com/wso2/docs-apim/pull/1287 | 3.1.0
https://github.com/wso2/docs-apim/pull/1288 | master

The file path in 3.1.0 and master is as follows:
https://apim.docs.wso2.com/en/latest/en/docs/administer/logging-and-monitoring/logging/monitoring-http-access-logs/
