### ISSUE TITLE
IS as KM needs to be used in the Kerberos OAuth2 Grant  scenario

### ISSUE THREAD

**Issue by shaniR** [wso2/docs-apim#1283]
**Description:**
Currently the scenario in the document uses the IWA Authenticator. This needs to be changed to use IS as KM.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:*3.0.0 onawards*

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by lathlk** [comment]
It's better to remove the content of the [1] and link the IS documentation[2].

[1] https://apim.docs.wso2.com/en/latest/learn/api-security/oauth2/grant-types/kerberos-oauth2-grant/#configuring-kerberos-grant-with-api-manager
[2] https://is.docs.wso2.com/en/5.9.0/learn/kerberos-grant/

**Comment by Mariangela** [comment]
@tharindu1st , in the case of APIM as the user will be using the IS-as-KM distribution as opposed to WSO2 IS, does it make sense to copy the content in [2] in to [1] and replace WSO2 IS with WSO2 IS as KM so that the doc will be more focused at APIM than just pointing off?


[1] https://apim.docs.wso2.com/en/latest/learn/api-security/oauth2/grant-types/kerberos-oauth2-grant/#configuring-kerberos-grant-with-api-manager
[2] https://is.docs.wso2.com/en/5.9.0/learn/kerberos-grant/

**Comment by tharindu1st** [comment]
@Mariangela , We can make content more clear on configuring the grant type in IS as KM and we will need to make IS as KM as pre-requisites.

**Comment by Mariangela** [comment]
Fixed in 

https://github.com/wso2/docs-apim/pull/1318 | 3.0.0
-- | --
https://github.com/wso2/docs-apim/pull/1319 | 3.1.0
https://github.com/wso2/docs-apim/pull/1320 | master
