### ISSUE TITLE
Update the Analytics data migration client in APIM 2.6.0

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/docs-apim#1532]
### Description:

This document[1] contains old Analytics data migration client, which has released in December of 2018. But there are many fixes released for that in November of 2019, they are not reflecting there. Please update with the latest jar. 

### Content Positioning in Documentation:

- Link:

- Heading (& Step):

- Any other reference:

---
#### Suggested Labels:

Urgent

#### Suggested Assignees:

[1]. https://docs.wso2.com/display/AM260/Upgrading+from+the+Previous+Release?preview=/28718536/103327536/wso2-api-migration-client.zip#260

**Comment by Mariangela** [comment]
Added the following ZIP in [1].
[wso2-api-migration-client.zip](https://github.com/wso2/docs-apim/files/4918023/wso2-api-migration-client.zip)


[1] https://docs.wso2.com/display/AM260/Upgrading+from+the+Previous+Release#250

**Comment by Mariangela** [comment]
Nadee Poornima reported as follows:
Yesterday, we saw the failed table was migrated successfully. Other tables also migrated. 
When doing the migration, I noticed, a logline(log info line), which I put when debugging the issue is still there. I have missed deleting before building the jar.  Therefore I rechecked the code and build the jar without that line. I tested the migration too. 

Therefore I am putting the updated jar here[1].
@Mariangela Hills (මරිඇන්ජලා හිල්ස්) could you please update the document with this jar.
[wso2-api-migration-client.zip](https://github.com/wso2/docs-apim/files/4924095/wso2-api-migration-client.zip)

**Comment by Mariangela** [comment]
@nadeepoornima , I updated [1] with the second ZIP that you sent
[1] https://docs.wso2.com/display/AM260/Upgrading+from+the+Previous+Release#250
