### ISSUE TITLE
Update 3.1.0 SOAP to REST documents after WUM updated

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/docs-apim#1584]
**Description:**
The following step needs to be added to the 3.1.0 doc [1]
Topics : Step 1 - Design a SOAP service as a REST API
6. Navigate to the Resources tab to view and edit you in/out sequences of the API.
[Add a screenshot as well]

Also add the following note:

Note: If you need to customize the swagger and sequences you will have to do these two processes separately.
1. Navigate to API Definition page and edit the swagger
2. Navigate Resources page and edit the sequences

[1] - [https://apim.docs.wso2.com/en/latest/learn/tutorials/expose-a-soap-service-as-a-rest-api/](https://apim.docs.wso2.com/en/latest/learn/tutorials/expose-a-soap-service-as-a-rest-api/)

**Comment by tmkasun** [comment]
Hi @kavishkafernando ,

I think the suggested step and the note are already there in the `Generate REST API from SOAP Backend` doc page in all 3.x doc spaces [3.2.0](https://apim.docs.wso2.com/en/latest/learn/design-api/create-api/generate-rest-api-from-soap-backend/#!), [3.1.0](https://apim.docs.wso2.com/en/3.1.0/learn/design-api/create-api/generate-rest-api-from-soap-backend/#!), [3.0.0](https://apim.docs.wso2.com/en/3.0.0/learn/design-api/create-api/generate-rest-api-from-soap-backend/#generate-rest-api-from-soap-backend).

The documentation page that you have pointed[1], explains how to create an API(SOAP) from WSDL which passes through the SOAP service traffic. In that scenario, we don't generate a REST API for the SOAP service. so there are no generated In and Out sequences that do the payload transformation.

The title of that documentation might have confused the user, Because it says

![image](https://user-images.githubusercontent.com/3313885/102963602-839f1900-450f-11eb-93b1-83143c2005d5.png)

```
Expose a SOAP service as a REST API
```
but what it actually does is create and invoke SOAP API.

I think the following statement has contradictory meanings in its middle and latter parts

```
This tutorial will explain the steps to design, publish and invoke a SOAP service as a RESTful API using Pass Through
``` 

When gateway passing through the SOAP requests we can't use it as a RESTFul API isn't it ?
 
@bhathiya , @tgtshanika , @shaniR WDYT ? 


[1]: https://apim.docs.wso2.com/en/latest/learn/tutorials/expose-a-soap-service-as-a-rest-api/

**Comment by bhathiya** [comment]
Before we had the generate feature, we used to call this SOAP to REST. But now we have a real SOAP to REST generation feature. So now we can call this SOAP passthrough. The value addition here is all the QoS the gateway adds.
