### ISSUE TITLE
[APIM 3.1.0 with ISKM_5.10.0] Key Manager cache configuration details

### ISSUE THREAD

**Issue by dumindurox777** [wso2/docs-apim#1804]
**Description:**
 We can configure the key cache by editing the following elements in the <APIM_HOME>/repository/conf/deployment.toml file.But if we enable "apim.cache.km_token" in <APIM_HOME>/repository/conf/deployment.toml, it should not use that config since it is the APIM node. Therefore we need to set those value on <IS_KM_HOME>/repository/conf/deployment.toml.But that details were not available on documnataion[1] Therefore we needed to  add those detail to the API manage official documnataion[1]

<img width="746" alt="Screen Shot 2020-08-26 at 4 33 07 PM" src="https://user-images.githubusercontent.com/29389251/91296380-23df6e00-e7ba-11ea-905d-65880c425238.png">

**Affected Product Version:**
APIM-3.1.0 IS_KM-5.10.0

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/advance-configurations/configuring-caching/#key-manager-cache

**Comment by Krishanx92** [comment]
Here we mentioned the APIM key manager cache, to enable that we need the above property "apim.cache.km_token" to be true.
Instead of APIM Key manger, if someone use IS KM then key manager configuration needs to set up from IS key manager side.

However, caching doc revamp with APIM-3.2.0 [1]. if you have further queries please raise an issue.

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/advance-configurations/configuring-caching/#!
