### ISSUE TITLE
GraphQL endpoint which has been referring at GraphQL doc is not working

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/docs-apim#1909]
**Description:**
Endpoint used at GraphQL docs[1][2][3][4] are not working 

[1] https://apim.docs.wso2.com/en/next/learn/design-api/create-api/create-a-graphql-api/
[2] https://apim.docs.wso2.com/en/next/learn/tutorials/create-and-publish-a-graphql-api/#create-and-publish-a-graphql-api
[3] https://apim.docs.wso2.com/en/latest/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console/#invoke-an-graphql-api-using-the-integrated-graphql-console
[4] https://apim.docs.wso2.com/en/next/learn/rate-limiting/graphql-api/overview-query-limits-for-graphql/

**Affected Product Version:**
3.x.x

**Comment by chanaka3d** [comment]
The doc URLs mentioned in the issue description has changed.
[1] https://apim.docs.wso2.com/en/latest/learn/design-api/create-api/create-a-graphql-api/
[2] https://apim.docs.wso2.com/en/latest/learn/tutorials/create-and-publish-a-graphql-api/#create-and-publish-a-graphql-api
[3] https://apim.docs.wso2.com/en/latest/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console/#invoke-an-graphql-api-using-the-integrated-graphql-console
[4] https://apim.docs.wso2.com/en/latest/learn/rate-limiting/graphql-api/overview-query-limits-for-graphql/

**Comment by chanaka3d** [comment]
I am unable to find a working hosted sample of Star Wars API.

https://graphql.org/swapi-graphql/

the above URL is working. But https://swapi-graphql.netlify.app/.netlify/functions/index which is the backend Gives CORS error.

The following sample is working fine with APIM.

https://countries-274616.ew.r.appspot.com/

The backend URL for this sample https://countries-274616.ew.r.appspot.com/ is not giving CORS errors. So we have to either rewrite the above docs using the working sample or host the Star Wars API somewhere and enable CORS.

**Comment by tmkasun** [comment]
Hi @chanaka3d,

Thanks for the inputs,
I think the root cause here is, 
We have instructed to use an external GraphQL endpoint (https://api.graph.cool/simple/v1/swapi) in our documentation and now it's no longer accessible.
This could happen even if a switch to a different online endpoint. So I think we have to take one of the following approaches

- Add a sample SDL and the relevant mock GraphQL implementation to the distribution, Similar to PizzaShak API. This will allow us to add a `Deploy Sample` kind of experience **later** and the whole example is self contain and easy to try out/setup
- Host our own sample GraphQL server externally and point that in our docs, [Example Building Serverless GraphQL API in Node with Express and Netlify](https://css-tricks.com/building-serverless-graphql-api-in-node-with-express-and-netlify/)
- Provide a mock GraphQL server in the documentation, So that users can download and run it locally and use its endpoint when trying out GraphQL API in the API Manager server

Please suggest any other alternative if none of the above are feasible.

@tgtshanika @bhathiya @sanjeewa-malalgoda @fazlan-nazeem @HiranyaKavishani any comments or preferences?

**Comment by bhathiya** [comment]
Yes, we should not depend on external endpoints. This is exactly what happened with the external Weather REST API as well. 

We should already have some sample service implementations with @HiranyaKavishani etc. right? Shall we ship something with 4.0? 

For the released versions, we can do the last option above.

**Comment by fazlan-nazeem** [comment]
+1 to ship one of our own services

**Comment by tgtshanika** [comment]
+1. We can do the same for SOAP endpoints as well.

**Comment by HiranyaKavishani** [comment]
+1 to ship the sample .war apps for GraphQL and SOAP endpoints with 4.0. @bhathiya yes, we have a sample GraphQL service implementation for a product management use case; but the current implementation has some limitations on query processing at the service layer. It doesn't cover whole scope as mentioned at SDL content :-( . So, it works for certain queries requested by client. BTW, I'll look on the feasibility of shipping it with 4.0

**Comment by HiranyaKavishani** [comment]
@tmkasun , @chanaka3d IMO for 3.x versions, we have to modify the document immediately with a working graphQL endpoint [1]. @fazlan-nazeem WDYT?

[1] http://snowtooth.moonhighway.com/

**Comment by tmkasun** [comment]
For my 3rd option, I tried this [mock server](https://github.com/apollographql/starwars-server) locally
and it seems a perfect match for our requirement

- It's has a mock for Star Wars scenario which is what we have used now 
- They have an MIT license so I think we can take a copy and use it in our docs (attach a zip file to docs)

WDYT ?

Shall we use this code ?

**Comment by fazlan-nazeem** [comment]
@tmkasun +1 for the idea. This way we will only have to slightly modify the docs.

**Comment by HiranyaKavishani** [comment]
@tmkasun great. Since this needs slight modification in endpoint section in existing docs, +1 to add the zip file and include the necessary steps to run it locally.
Thanks!

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commits
