### ISSUE TITLE
[Doc] Limitations on having curly braces ({ }) characters in Admin Credentials

### ISSUE THREAD

**Issue by athiththan11** [wso2/docs-apim#2099]
**Description:**

Add a note to the documentation specifying the limitations on using curly braces ({ }) in the Super Admin password credentials.

**Affected Product Version:**

- WSO2 API Manager v3.2.0

**Comment by Mariangela** [comment]
@athiththan11 ,for example when we say not to add the % sign we say "This parsing exception happens because the percentage (%) sign acts as the escape character in URL parsing." 
What can we specify as the reason for this? 

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords/#change-the-super-admin-credentials

**Comment by isharac** [comment]
"${" and "}" are reserved characters as they are used to identify the properties that are specified as system properties.
