### ISSUE TITLE
API Analytics Migration from 2.1.0 to 3.2.0

### ISSUE THREAD

**Issue by harshanL** [wso2/docs-apim#2233]
**Description:**
The document on guiding API analytics migration (step 3.2 - 1) is misleading. The document emphasizes use of APIM 2.1.0 AM_DB but we have to use the migrated APIM 3.2.0 AM_DB when running the migration client.
![image](https://user-images.githubusercontent.com/6368301/98911038-fb7a2c80-24e9-11eb-882e-86dc6c8f4558.png)

[https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320/#step-32-configure-wso2-api-m-320-for-analytics-and-migrate-data-into-new-analytics-database](url)

**Suggested Labels:**
apim-3.2.0, migration, analytics

**Suggested Assignees:**

**Affected Product Version:**
3.2.0

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

**Comment by Meruja** [comment]
API-M has to point the new migrated DB and Analytics has to point the previous version AM DB. This is the ideal way because when writing the analytics migration client we have used the schema which was there at that time(the older versions schema) to query the data, so any significant changes to the table or columns in am_db which are used by the analytics migration client can break the client if we use the migrated DB.

**Comment by Meruja** [comment]
Configuring new migrated DB is convenient based on the User experience and considering that schema changes are not very often in API manager.
