### ISSUE TITLE
[APIM 3.2.0] [configure-wso2is-connector] shared artifacts are outdated. 

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/docs-apim#2491]
Hi Team,

The shared artifacts in step 3 under the heading "Step 1 - Configure WSO2 IS" are outdated. Shall we take a step to share the latest artifacts by attaching them to the documentation?

[1] https://apim.docs.wso2.com/en/latest/administer/key-managers/configure-wso2is-connector/

**Comment by Mariangela** [comment]
@SiluniPathirana , please confirm as to which version we should link in the 3.2.0 docs from here [1]

[1] https://github.com/wso2-extensions/apim-km-wso2is/tags

**Comment by Mariangela** [comment]
Siluni had provided more information on this issue offline as follows:

Users are configuring WSO2 IS 5.10.0 as the key manager with APIM 3.2.0 latest WUM update, by installing the artifacts available in the [2]. Since the artifacts ("keymanager-operations.war") shared in the documentation does not include the latest fix [3]. Users are still experiencing the issue even though they use the latest WUM updates

The shared artifacts in step 3 under the heading "Step 1 - Configure WSO2 IS" are outdated. Shall we take a step to share the latest artifacts by attaching them to the documentation?

Thanks,
Siluni


[2] https://apim.docs.wso2.com/en/latest/administer/key-managers/configure-wso2is-connector/
[3] https://github.com/wso2-extensions/apim-km-wso2is/pull/30/commits/f8fe73885dfcc999ea176b9d3ea036c21c7e81b6

**Comment by SiluniPathirana** [comment]
[](url)

**Comment by Mariangela** [comment]
@SiluniPathirana , Please share the WAR file that is needed for this fix.

**Comment by Mariangela** [comment]
Ishara fixed this in 3.2.0 via this PR https://github.com/wso2/docs-apim/pull/2494

**Comment by Mariangela** [comment]
Fixed in master via https://github.com/wso2/docs-apim/pull/2561
