### ISSUE TITLE
Doc Feedback: Lack of guidance on enabling the page and making customizations.

### ISSUE THREAD

**Issue by lakshikap** [wso2/docs-apim#2945]
Hi,

This page needs to include information on how to exactly enable it by adding the code component. 
Then it needs to include how the text in the json file can be edited/ changed.

Please speak to ChanakaJ as I have chatted about it with him. 

Location : https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/enable-or-disable-home-page/

**Comment by Mariangela** [comment]
@chanaka3d , as mentioned offline please work on this task.

**Comment by wasuradananjith** [comment]
As per the discussion with @chanaka3d , the below content in the **Overriding Developer Portal Theme** should be repeated in every subsequent page (such as **Enable or Disable Rating**, **Enable or Disable Home Page** etc).

![image](https://user-images.githubusercontent.com/25246848/106565954-a03e6000-6555-11eb-9ee5-4e9f5d28268d.png)

The reason for the need of repetition is, if a user go directly to a page like **Enable or Disable Rating** he/she might get confused. As a solution we can repeat the content. There are two (2) methods to do this.
1. We can repeat the above content in the screenshot as it is in every page.
2. We can point to the above page from other pages (using a tip/info/note), so that users may refer it.

Even the method 1 has **the disadvantage of repeating the content as it is**, it might be more user friendly since the users may not get lost by navigating to the links from one place to another. For example, if someone has started reading **Enable or Disable Home Page**, if we use the method 2, that person will be navigated to the **Overriding Developer Portal Theme** and may get lost there. (He/she may be confused from where did he/she reach that place)

Any ideas? @chanaka3d and @Mariangela
