### ISSUE TITLE
Incorrect code in 3.2.0

### ISSUE THREAD

**Issue by kalevivek11** [wso2/docs-apim#3177]
https://apim.docs.wso2.com/en/latest/develop/extending-api-manager/extending-gateway/writing-custom-handlers/

line no 153
code should have imported
 import org.wso2.carbon.apimgt.gateway.handlers.security.APISecurityException;

otherwise, it throws compilation error

**Comment by Mariangela** [comment]
@ kalevivek11, thank you for reporting this issue. 
We will add the proposed fix to the documentation after getting further clarification from a subject matter expert at WSO2.

**Comment by pubudu538** [comment]
Yes, we need to add the above line to the code sample of CustomAPIAuthenticationHandler.  This is already fixed in the sample that is available to download. 

There is another missing link in this page. There is an artifact available to download. ( Search for "A sample implementation is here." ) This downloads invalid content. I guess we don't need this part. So we should fix that too.
