### ISSUE TITLE
Please review the doc for 3.0.0 for Minimum High Availability Deployment for WSO2 APIM Analytics

### ISSUE THREAD

**Issue by vanjikumaran** [wso2/docs-apim#441]
Please review the doc for 3.0.0 for Minimum High Availability Deployment for WSO2 APIM Analytics.
Doc is not formatted correctly.

<img width="742" alt="Screen Shot 2019-11-19 at 11 19 34 AM" src="https://user-images.githubusercontent.com/3397321/69178524-a82ff280-0abe-11ea-894b-0b1980bab25a.png">

**Comment by vanjikumaran** [comment]
what is the update on this issue?

**Comment by Mariangela** [comment]
@ruks , based on our offline discussion, I removed this page from mkdocs.yml and moved it to the need-to-update folder as the content is outdated. Let us know after you have updated this content so that we can review it further.

https://github.com/wso2/docs-apim/pull/802/commits/41c0c961b5d3c329a5f15dd174ab5ee7cfe2e095

**Comment by Mariangela** [comment]
This has been fixed in https://github.com/wso2/docs-apim/pull/824
