### ISSUE TITLE
Doc Feedback: Configure the Publisher with a single Traffic Manager as follows misses ""

### ISSUE THREAD

**Issue by robbla** [wso2/docs-apim#557]
Location : https://apim.docs.wso2.com/en/latest/InstallAndSetup/DeployingWSO2APIManager/DistributedDeployment/deploying-wso2-api-m-in-a-distributed-setup/

the  config showsn for the traffic manager 

[apim.throttling]
    service_url = https://Traffic-Manager-host:${mgt.transport.https.port}/services/
    throttle_decision_endpoints = ["tcp://Traffic-Manager-host:5672"]

    [[apim.throttling.url_group]]
    traffic_manager_urls = ["tcp://Traffic-Manager-host:9611"]
    traffic_manager_auth_urls = ["ssl://Traffic-Manager-host:9711"]

misses the "" on the service_url

**Comment by Mariangela** [comment]
Fixed in 
- https://github.com/wso2/docs-apim/pull/777/commits/6422f64b12d55a4e4ee4b27a74a85aa9f4690032
- https://github.com/wso2/docs-apim/pull/777

- https://apim.docs.wso2.com/en/latest/install-and-setup/deploying-wso2-api-manager/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup/
