### ISSUE TITLE
Change the "ThrottleHandler" when migrating from 2.x series to 3.x series when disable the advanced throttling on the 2.xpack

### ISSUE THREAD

**Issue by vinok88** [wso2/docs-apim#5598]
**Description:**
Fixes done in https://github.com/wso2/docs-apim/pull/2529 should be merged to newer APIM versions as well.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.2, 4.0, 4.1
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
refer to https://github.com/wso2/product-apim/issues/9631

**Related Issues:**
https://github.com/wso2/product-apim/issues/9631

**Comment by Mariangela** [comment]
Hi @vinok88 ,

This has been fixed via the following PRs in the 3.x docs.

- 3.2.0 - https://github.com/wso2/docs-apim/pull/5963
- 3.0.0 - https://github.com/wso2/docs-apim/pull/5977

Sachini mentioned that we don't have that script in 4.0.0, since we have the in memory deployer, so no changes in 4.0.0 docs. 

Therefore, I am resolving this issue.

Related to - This issue maps to A-274
