### ISSUE TITLE
Migration documentations/links are missing under upgrade section in APIM 4.1.0 documentation

### ISSUE THREAD

**Issue by isuru-udayanga** [wso2/docs-apim#5694]
**Description:**
WSO2 APIM upgrade documentation links for only 4.0.0 to 4.1.0 and 3.2.0 to 4.1.0 (Left hand side navigation) under upgrade section in APIM 4.1.0 documentation. There should be other versions as well (2.x versions too).

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:** WSO2 API Manager 4.1.0

**OS, DB, other environment details and versions:**    N/A

**Steps to reproduce:**
Access this link - https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-guidelines/
and see left hand side navigation bar.

**Related Issues:**

**Comment by Mariangela** [comment]
Hi @isuru-udayanga , 

Thank you for reporting this issue!
These pages are actually work in progress and they will be available soon. Therefore, in order to avoid any further confusion, we added these pages to the left navigation and also added Work In Progress banners in each of these pages for the moment via PR [1].
 
<img width="1680" alt="Screenshot 2022-04-22 at 8 09 29 PM" src="https://user-images.githubusercontent.com/5195851/164739697-9dd1de67-5546-47ab-a616-2665a76eab0c.png">

We will update this ticket as soon as these pages are released.

[1] https://github.com/wso2/docs-apim/pull/5704

Regards,

Mariangela Hills

**Comment by samgnaniah** [comment]
This is fixed now so closing this.
