### ISSUE TITLE
[APIM 2.6.0] - Sharing Applications document should be changed

### ISSUE THREAD

**Issue by SupunTharakaSandaruwan** [wso2/docs-apim#642]
**Description:**

The document [1] says if the group sharing is enabled and the **Group ID**s are not entered in the **Groups** section, a particular application will be shared with the users who are in the same organization. 
But that does not work as explained in APIM 2.6.0 because it is not the expected behavior of it. Therefore this instruction needs to be removed from [1].

[1] https://docs.wso2.com/display/AM260/Sharing+Applications

**Affected Product Version:** APIM 2.6.0

<img width="1324" alt="Screen Shot 2020-01-13 at 9 16 48 AM" src="https://user-images.githubusercontent.com/26220675/72232210-a0d02580-35e5-11ea-98e7-52c2c315ea88.png">

**Comment by Mariangela** [comment]
@bhathiya , please comment.

**Comment by bhathiya** [comment]
This comes from old versions. Let's remove it from 2.6.0 and 2.5.0.

**Comment by Mariangela** [comment]
Removed in 2.6.0 and 2.5.0.
- https://docs.wso2.com/display/AM260/Sharing+Applications
- https://docs.wso2.com/display/AM250/Sharing+Applications

**Comment by Mariangela** [comment]
As this was removed in 2.6.0, removed this from 3.0.0 as well. @bhathiya , pls let me know if you have any concerns.

Fixed in 
- https://github.com/wso2/docs-apim/pull/789
- https://github.com/wso2/docs-apim/pull/789/commits/d0eb848cd0aa78498d11e19fba166d31c00c3365
- https://apim.docs.wso2.com/en/latest/learn/consume-api/manage-application/sharing-applications/sharing-applications/#sharing-an-application-with-multiple-users
