### ISSUE TITLE
API Categories page needs to be updated 

### ISSUE THREAD

**Issue by erangatl** [wso2/docs-apim#724]
Location : https://apim.docs.wso2.com/en/next/Learn/ConsumeAPI/Customizations/CustomizingTheDeveloperPortal/CustomizeAPIListing/categorizing-and-grouping-apis/

![image](https://user-images.githubusercontent.com/20179540/74724067-af070680-5261-11ea-8198-fe2093cfcc96.png)

**Comment by Mariangela** [comment]
The fix is available in -
- [3.1.0](https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/customize-api-listing/categorizing-and-grouping-apis/api-category-based-grouping/#api-category-based-grouping)
- [master](https://apim.docs.wso2.com/en/next/develop/customizations/customizing-the-developer-portal/customize-api-listing/categorizing-and-grouping-apis/api-category-based-grouping/#add-an-api-category-using-the-admin-rest-api)
