### ISSUE TITLE
Missing images in the API Manager Documentation 3.0.0 

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/docs-apim#822]
**Description:**
Found some images are missing under the topic "learn" as listed below.

- The image under the point "Sign in to the API Publisher and click CREATE API" is missing in the below links.
https://github.com/wso2/docs-apim/blob/master/en/docs/learn/design-api/create-api/generate-rest-api-from-soap-backend.md
https://github.com/wso2/docs-apim/blob/master/en/docs/learn/design-api/create-api/expose-a-soap-service-as-a-rest-api.md
https://github.com/wso2/docs-apim/blob/master/en/docs/learn/tutorials/expose-a-soap-service-as-a-rest-api.md

- The image under the point "Click GENERATE button, generated JWT token can be seen at the popup and copy it" is missing in below link.
https://github.com/wso2/docs-apim/blob/master/en/docs/learn/tutorials/expose-a-soap-service-as-a-rest-api.md

- The image under the point "Click on the lifecycle state change buttons to change the lifecycle state" is missing in the below link.
https://github.com/wso2/docs-apim/blob/master/en/docs/learn/design-api/lifecycle-management/api-lifecycle.md

Reuploading the relevant images may solve the problem.

**Affected Product Version:**
APIM 3.0

**Comment by Mariangela** [comment]
Fixed in 
- https://github.com/wso2/docs-apim/pull/831
- https://github.com/wso2/docs-apim/pull/833
Fixed in the following pages:
- https://apim.docs.wso2.com/en/latest/learn/design-api/create-api/generate-rest-api-from-soap-backend/
- https://apim.docs.wso2.com/en/latest/learn/design-api/create-api/expose-a-soap-service-as-a-rest-api/
- https://apim.docs.wso2.com/en/latest/learn/tutorials/expose-a-soap-service-as-a-rest-api/
- https://apim.docs.wso2.com/en/latest/learn/design-api/lifecycle-management/api-lifecycle/
