### ISSUE TITLE
Incorrect commands in Working with Observability

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/docs-apim#872]
**Description:**

**-H** needed before activityId
![image](https://user-images.githubusercontent.com/32578617/77084513-106af280-6a25-11ea-8996-c92368d1f043.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0.0
3.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
@Arshardh , please confirm.

@sanjulamadurapperuma , is this applicable for API-M 3.0.0 and 3.1.0 docs as well?

**Comment by Arshardh** [comment]
Yes, the first issue with the -H flag should be fixed by adding -H before the activity id header.

But in the second case the '|' character is dropped on purpose as we get HTTP correlation logs in the following different formats and in order to accommodate both of these kinds we need to have a common value.
**|HTTP** State Transition|
**|HTTP**|

**Comment by sanjulamadurapperuma** [comment]
Yes, with regards to the second point, @Arshardh is right. It doesn't seem to be an issue. Will remove it, thanks!

**Comment by sanjulamadurapperuma** [comment]
@Mariangela yes this is applicable for both APIM-3.0.0 and 3.1.0 docs

**Comment by Mariangela** [comment]
Fixed in -
- 3.0.0 - https://github.com/wso2/docs-apim/pull/895
- 3.1.0 - https://github.com/wso2/docs-apim/pull/896
